# Generated by Django 3.2.5 on 2021-07-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_cart", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Order",
            new_name="Cart",
        ),
    ]
