# Generated by Django 3.2.5 on 2021-07-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_cart", "0002_rename_order_cart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="products",
            name="image",
            field=models.ImageField(null=True, upload_to="upload/"),
        ),
    ]
